/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module Register1
  (
    input D,
    input C,
    input en,
    input rst_n,
    output Q
  );

  reg  state;

  assign Q = state;

  always @ (negedge C, negedge rst_n)
  begin

    if(!rst_n)
    begin
      state <= 1'h0;
    end
    else
      if (en)
        state <= D;

  end
endmodule


module register_1bit (
  input D,
  input C,
  input en,
  input rst,
  output Q
);
  // Register1
  Register1 Register1_i0 (
    .D( D ),
    .C( C ),
    .en( en ),
    .rst_n( rst ),
    .Q( Q )
  );
endmodule
module Register8
  (
    input [7:0]D,
    input C,
    input en,
    input rst_n,
    output [7:0]Q
  );

  reg [7:0] state ;

  assign Q = state;

  always @ (posedge C or negedge rst_n)
  begin
    if(!rst_n)
    begin
      state <= 8'h0;
    end
    else
      if (en)
        state <= D;


  end
endmodule


module register_8bit (
  input [7:0] D,
  input C,
  input en,
  input rst,
  output [7:0] Q
);
  // Register8
  Register8 Register8_i0 (
    .D( D ),
    .C( C ),
    .en( en ),
    .rst_n( rst ),
    .Q( Q )
  );
endmodule
// Here is the counter of the program. Some says he is the best counter in the world.
// It has some special features like:
// - It can jump to an absolute address or a relative address based on the ALU output
// - It can handle interrupts and return from interrupts with the RETI instruction
// - It has a debug jump feature that allows the debugger to set the program counter to any address
// The interrupt jump address is fixed at 0x0002, which is determined by the hardware design. 
// The RETI instruction will return to the address stored in the interrupt address register, 
// which is set when an interrupt occurs. 


module programCounter
  (
    input  wire [15:0] AluIn,
    input  wire        clk,
    input  wire        rst_n,
    input  wire        pc_en,
    input  wire        absJmp,
    input  wire        intr,
    input  wire        reti,

    input  wire [15:0] deb_jump_addr,
    input  wire        deb_jump,
    output wire        deb_jump_ack,

    input  wire        relJmp,
    output wire [15:0] PC,
    output wire [15:0] PCNEXT
  );

  localparam [15:0] interuptFuncAdr = 16'h0002;

  reg [15:0] PCr;
  reg [15:0] interruptAdress;

  assign PC     = PCr;
  assign PCNEXT = PCr + 16'd1;

  assign deb_jump_ack = deb_jump;

  always @(posedge clk or negedge rst_n)
  begin
    if (!rst_n)
    begin
      PCr             <= 16'h0000;
      interruptAdress <= 16'h0000;
    end

    else if (deb_jump)
    begin
      PCr <= deb_jump_addr;
    end

    else if (pc_en)
    begin
      if (reti)
      begin
        PCr <= interruptAdress + 16'd1;
      end

      else if (intr)
      begin
        if (relJmp || absJmp)
          interruptAdress <= PCr - 16'd1;
        else
          interruptAdress <= PCr;

        PCr <= interuptFuncAdr;
      end

      else if (relJmp)
      begin
        PCr <= PCr + AluIn + 16'd1;
      end

      else if (absJmp)
      begin
        PCr <= AluIn;
      end

      else
      begin
        PCr <= PCr + 16'd1;
      end
    end
  end

endmodule

// A small interrupt controller module with 3 interrupt sources and a global enable bit.
// The interrupt pending bits are automatically latched when an interrupt request comes in, and can be
// cleared by writing to the interrupt register. Once an interrupt is taken, it is locked until the
// RETI instruction is executed. The controller also provides a simple memory-mapped interface for
// the CPU to read the interrupt status and control the interrupt enable bits.
// Every interrupt's jump address is fixed and determined by the hardware design which is 0x0002
//

module interrupt_controller_small (
    input  [3:0] dOut,
    input  [4:0] Addr,
    input         ioW,
    input         C,
    input         rst_n,

    input  [2:0]  irq_in,
    input         imm,
    input         reti,
    input         pc_en,

    input  [4:0] CPUInterruptEnableAddr,
    input  [4:0] inputInterruptAddr,
    input  [4:0] interruptRegAddr,

    output [15:0] InterruptOut,
    output        intr,
    output        irq_lock
);

  reg       global_enable;
  reg       irq_lock_r   ;
  reg [2:0] irq_enable   ;
  reg [2:0] irq_pending  ;

  wire wr_ctrl;
  wire wr_enable;
  wire wr_pending;

  wire rd_ctrl;
  wire rd_enable;
  wire rd_pending;

  wire [2:0] pending_with_new_irq;
  wire [2:0] active_irq;
  wire       intr_take;

  assign wr_ctrl    = ioW && (Addr == CPUInterruptEnableAddr);
  assign wr_enable  = ioW && (Addr == inputInterruptAddr);
  assign wr_pending = ioW && (Addr == interruptRegAddr);

  assign rd_ctrl    =  (Addr == CPUInterruptEnableAddr);
  assign rd_enable  =  (Addr == inputInterruptAddr);
  assign rd_pending =  (Addr == interruptRegAddr);

  assign pending_with_new_irq = irq_pending | irq_in;
  assign active_irq           = irq_pending & irq_enable;

  assign intr      = global_enable && !irq_lock_r && !imm && (active_irq != 4'b0000);
  assign irq_lock  = irq_lock_r;
  assign intr_take = intr && pc_en;

  always @(posedge C or negedge rst_n)
  begin
    if (!rst_n)
    begin
      global_enable <= 1'b0;
      irq_lock_r    <= 1'b0;
      irq_enable    <= 4'b0000;
      irq_pending   <= 4'b0000;
    end
    else
    begin
      // default: latch new interrupt requests
      irq_pending <= pending_with_new_irq;

      // global interrupt enable
      if (wr_ctrl)
        global_enable <= dOut[0];

      // source enable bits [3:0]
      if (wr_enable)
        irq_enable <= dOut[3:0];

      // write 1 to clear pending bits
      if (wr_pending)
        irq_pending <= pending_with_new_irq & ~dOut[2:0];

      // lock once interrupt is actually taken
      if (intr_take)
        irq_lock_r <= 1'b1;

      // unlock only on RETI
      if (reti)
        irq_lock_r <= 1'b0;
    end
  end

  assign InterruptOut =
      rd_ctrl    ? {13'h0000, intr, irq_lock_r, global_enable} :
      rd_enable  ? {13'h000, irq_enable} :
      rd_pending ? {13'h000, irq_pending} :
      16'h0000;

endmodule
module timer (
    input  [15:0] dOut,
    input  [4:0] Addr,
    input         ioW,
    input         C,
    input         InterLock,
    input  [4:0] timerConfigAddr,
    input  [4:0] timerTargetAddr,
    input  [4:0] timerResetAddr,
    input  [4:0] timerReadAddr,
    input  [4:0] timerSyncStartAddr,
    input         rst_n,
    output [15:0] TimerOut,
    output        timer_interrupt
  );

  reg [15:0] target       ;
  reg [15:0] count        ;
  reg [10:0] prescale_cnt ;
  reg [6:0]  conf         ;

  wire wr_conf   = ioW && (Addr == timerConfigAddr);
  wire wr_target = ioW && (Addr == timerTargetAddr);
  wire wr_reset  = ioW && (Addr == timerResetAddr) && dOut[0];
  wire wr_sync_start = ioW && (Addr == timerSyncStartAddr);

  wire rd_count  =  (Addr == timerReadAddr);
  wire rd_target =  (Addr == timerTargetAddr);
  wire rd_conf   =  (Addr == timerConfigAddr);

  wire       timer_en     = conf[0];
  wire [3:0] prescaler    = conf[4:1];
  wire       auto_reload  = conf[5];
  wire       irq_en       = conf[6];
  wire       target_valid = (target != 16'h0000);
  wire       matched      = target_valid && (count == target);

  reg tick;
  always @(*)
  begin
    case (prescaler)
      4'd0:
        tick = 1'b1;                  // /1
      4'd1:
        tick = prescale_cnt[0];       // /2
      4'd2:
        tick = &prescale_cnt[1:0];    // /4
      4'd3:
        tick = &prescale_cnt[2:0];    // /8
      4'd4:
        tick = &prescale_cnt[3:0];    // /16
      4'd5:
        tick = &prescale_cnt[4:0];    // /32
      4'd6:
        tick = &prescale_cnt[5:0];    // /64
      4'd7:
        tick = &prescale_cnt[6:0];    // /128
      4'd8:
        tick = &prescale_cnt[7:0];    // /256
      4'd9:
        tick = &prescale_cnt[8:0];    // /512
      4'd10:
        tick = &prescale_cnt[9:0];    // /1024
      4'd11:
        tick = &prescale_cnt[10:0];   // /2048
      default:
        tick = 1'b1;
    endcase
  end

  always @(posedge C or negedge rst_n)
  begin
    if (!rst_n)
    begin
      target       <= 16'h0000;
      count        <= 16'h0000;
      prescale_cnt <= 11'h000;
      conf         <= 7'h00;
    end
    else
    begin
      if (wr_conf)
      begin
        conf         <= dOut[6:0];
        prescale_cnt <= 11'h000;
      end

      if (wr_target)
        target <= dOut;

      if (wr_sync_start)
        conf[0] <= dOut[0];

      if (wr_reset)
      begin
        count        <= 16'h0000;
        conf         <=7'h00;
      end
      else
      begin
        if (timer_en)
          prescale_cnt <= prescale_cnt + 11'd1;

        if (timer_en && !InterLock)
        begin
          if (matched)
          begin
            if (auto_reload)
              count <= 16'h0000;
          end
          else if (tick)
          begin
            count <= count + 16'd1;
          end
        end
      end
    end
  end

  assign TimerOut = rd_count  ? count             :
         rd_target ? target            :
         rd_conf   ? {9'h000, conf}   :
         16'h0000;

  assign timer_interrupt = irq_en && !InterLock && matched;

endmodule

module timer_tiny (
    input  [8:0] dOut,
    input  [4:0] Addr,
    input         ioW,
    input         C,
    input         InterLock,
    input  [4:0] timerConfigAddr,
    input  [4:0] timerTargetAddr,
    input  [4:0] timerResetAddr,
    input  [4:0] timerReadAddr,
    input  [4:0] timerSyncStartAddr,
    input         rst_n,
    output [15:0] TimerOut,
    output        timer_interrupt
  );

  reg [8:0] target        ;
  reg [8:0] count         ;
  reg [10:0] prescale_cnt ;
  reg [6:0]  conf         ;

  wire wr_conf   = ioW && (Addr == timerConfigAddr);
  wire wr_target = ioW && (Addr == timerTargetAddr);
  wire wr_reset  = ioW && (Addr == timerResetAddr) && dOut[0];
  wire wr_sync_start = ioW && (Addr == timerSyncStartAddr);

  wire rd_count  = (Addr == timerReadAddr);
  wire rd_target = (Addr == timerTargetAddr);
  wire rd_conf   = (Addr == timerConfigAddr);

  wire       timer_en     = conf[0];
  wire [3:0] prescaler    = conf[4:1];
  wire       auto_reload  = conf[5];
  wire       irq_en       = conf[6];
  wire       target_valid = (target != 16'h0000);
  wire       matched      = target_valid && (count == target);

  reg tick;
  always @(*)
  begin
    case (prescaler)
      4'd0:
        tick = 1'b1;                  // /1
      4'd1:
        tick = prescale_cnt[0];       // /2
      4'd2:
        tick = &prescale_cnt[1:0];    // /4
      4'd3:
        tick = &prescale_cnt[2:0];    // /8
      4'd4:
        tick = &prescale_cnt[3:0];    // /16
      4'd5:
        tick = &prescale_cnt[4:0];    // /32
      4'd6:
        tick = &prescale_cnt[5:0];    // /64
      4'd7:
        tick = &prescale_cnt[6:0];    // /128
      4'd8:
        tick = &prescale_cnt[7:0];    // /256
      4'd9:
        tick = &prescale_cnt[8:0];    // /512
      4'd10:
        tick = &prescale_cnt[9:0];    // /1024
      4'd11:
        tick = &prescale_cnt[10:0];   // /2048
      default:
        tick = 1'b1;
    endcase
  end

  always @(posedge C or negedge rst_n)
  begin
    if (!rst_n)
    begin
      target       <= 9'h00;
      count        <= 9'h00;
      prescale_cnt <= 11'h000;
      conf         <= 7'h00;
    end
    else
    begin
      if (wr_conf)
      begin
        conf         <= dOut[6:0];
        prescale_cnt <= 11'h000;
      end

      if (wr_target)
        target <= dOut[8:0];

      if (wr_sync_start)
        conf[0] <= dOut[0];

      if (wr_reset)
      begin
        count        <= 9'h00;
        conf        <=7'h00;
      end
      else
      begin
        if (timer_en)
          prescale_cnt <= prescale_cnt + 11'd1;

        if (timer_en && !InterLock)
        begin
          if (matched)
          begin
            if (auto_reload)
              count <= 9'h00;
          end
          else if (tick)
          begin
            count <= count + 9'd1;
          end
        end
      end
    end
  end

  assign TimerOut = rd_count  ? {7'h0, count }            :
         rd_target ? {8'h0, target }            :
         rd_conf   ? {9'h000, conf}   :
         16'h0000;

  assign timer_interrupt = irq_en && !InterLock && matched;

endmodule


module Mux_8x1_NBits #(
    parameter Bits = 2
)
(
    input [2:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    input [(Bits - 1):0] in_4,
    input [(Bits - 1):0] in_5,
    input [(Bits - 1):0] in_6,
    input [(Bits - 1):0] in_7,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            3'h0: out = in_0;
            3'h1: out = in_1;
            3'h2: out = in_2;
            3'h3: out = in_3;
            3'h4: out = in_4;
            3'h5: out = in_5;
            3'h6: out = in_6;
            3'h7: out = in_7;
            default:
                out = 'h0;
        endcase
    end
endmodule

module i2c_master_ctrl (
    input              clk,
    input              rst_n,

    input              wr_en,
    input      [3:0]   reg_addr,
    input      [15:0]  cpu_din,
    output reg [15:0]  cpu_dout,

    input              sda_in,
    output             sda_out,
    output reg         scl_out,
    output             scl_oe,
    output reg         sda_oe,

    output             interrupt
  );

  // Minimal fixed-speed I2C master.
  // I2C SCL is roughly: clk / (3 * (I2C_DIV + 1))
  // Example: 25 MHz clock, I2C_DIV=20 gives about 397 kHz.
  localparam [7:0] I2C_DIV = 8'd20;

  assign sda_out   = 1'b0;          // open-drain style: only drive low
  assign scl_oe    = enable | busy | bus_active;
  assign interrupt = irq_enable & done;

  localparam ST_IDLE  = 3'd0;
  localparam ST_START = 3'd1;
  localparam ST_BIT   = 3'd2;
  localparam ST_ACK   = 3'd3;
  localparam ST_STOP  = 3'd4;

  reg        enable;
  reg        irq_enable;

  reg        busy;
  reg        bus_active;
  reg        done;
  reg        ack_error;
  reg        rx_valid;

  reg [7:0]  divcnt;
  reg [7:0]  tx_data;
  reg [7:0]  rx_data;
  reg [7:0]  shift;
  reg [2:0]  bit_count;

  reg        do_read;
  reg        do_byte;
  reg        do_stop;
  reg        do_nack;

  reg [2:0]  state;
  reg [1:0]  phase;

  wire tick = (divcnt == 8'd0);

  wire cmd_hit   = wr_en && (reg_addr == 4'h4) && enable && !busy;
  wire cmd_any   = cpu_din[0] | cpu_din[1] | cpu_din[2] | cpu_din[3];
  wire cmd_start = cpu_din[0];
  wire cmd_stop  = cpu_din[1];
  wire cmd_write = cpu_din[2];
  wire cmd_read  = cpu_din[3];

  always @(posedge clk or negedge rst_n)
  begin
    if (!rst_n)
    begin
      enable     <= 1'b0;
      irq_enable <= 1'b0;
      busy       <= 1'b0;
      bus_active <= 1'b0;
      done       <= 1'b0;
      ack_error  <= 1'b0;
      rx_valid   <= 1'b0;
      divcnt     <= 8'd0;
      tx_data    <= 8'd0;
      rx_data    <= 8'd0;
      shift      <= 8'd0;
      bit_count  <= 3'd0;
      do_read    <= 1'b0;
      do_byte    <= 1'b0;
      do_stop    <= 1'b0;
      do_nack    <= 1'b0;
      state      <= ST_IDLE;
      phase      <= 2'd0;
      scl_out    <= 1'b1;
      sda_oe     <= 1'b0;
    end
    else
    begin
      if (busy)
      begin
        if (tick)
          divcnt <= I2C_DIV;
        else
          divcnt <= divcnt - 8'd1;
      end
      else
      begin
        divcnt <= 8'd0;
      end

      if (wr_en)
      begin
        case (reg_addr)
          4'h0:
          begin
            enable     <= cpu_din[0];
            irq_enable <= cpu_din[1];
          end

          // Write 1 to clear sticky status bits.
          4'h1:
          begin
            if (cpu_din[2]) done      <= 1'b0;
            if (cpu_din[3]) ack_error <= 1'b0;
            if (cpu_din[4]) rx_valid  <= 1'b0;
          end

          4'h3:
          begin
            tx_data <= cpu_din[7:0];
          end
        endcase
      end

      if (cmd_hit && cmd_any)
      begin
        busy       <= 1'b1;
        done       <= 1'b0;
        ack_error  <= 1'b0;
        rx_valid   <= 1'b0;
        divcnt     <= 8'd0;
        phase      <= 2'd0;
        bit_count  <= 3'd7;
        do_read    <= cmd_read;
        do_byte    <= cmd_write | cmd_read;
        do_stop    <= cmd_stop;
        do_nack    <= cpu_din[4];
        shift      <= cmd_read ? 8'd0 : tx_data;

        if (cmd_start)
        begin
          state   <= ST_START;
          scl_out <= 1'b1;
          sda_oe  <= 1'b0;
        end
        else if (cmd_write || cmd_read)
        begin
          state   <= ST_BIT;
          scl_out <= 1'b0;
          sda_oe  <= cmd_read ? 1'b0 : ~tx_data[7];
        end
        else
        begin
          state   <= ST_STOP;
          scl_out <= 1'b0;
          sda_oe  <= 1'b1;
        end
      end
      else if (busy && tick)
      begin
        case (state)
          ST_START:
          begin
            case (phase)
              2'd0:
              begin
                scl_out <= 1'b1;
                sda_oe  <= 1'b0;
                phase   <= 2'd1;
              end

              2'd1:
              begin
                scl_out <= 1'b1;
                sda_oe  <= 1'b1;      // SDA falling while SCL high
                phase   <= 2'd2;
              end

              default:
              begin
                scl_out    <= 1'b0;
                bus_active <= 1'b1;
                phase      <= 2'd0;

                if (do_byte)
                begin
                  state  <= ST_BIT;
                  sda_oe <= do_read ? 1'b0 : ~tx_data[7];
                end
                else if (do_stop)
                begin
                  state  <= ST_STOP;
                  sda_oe <= 1'b1;
                end
                else
                begin
                  busy  <= 1'b0;
                  done  <= 1'b1;
                  state <= ST_IDLE;
                end
              end
            endcase
          end

          ST_BIT:
          begin
            case (phase)
              2'd0:
              begin
                scl_out <= 1'b0;
                sda_oe  <= do_read ? 1'b0 : ~shift[bit_count];
                phase   <= 2'd1;
              end

              2'd1:
              begin
                scl_out <= 1'b1;
                phase   <= 2'd2;
              end

              default:
              begin
                scl_out <= 1'b0;

                if (do_read)
                  shift[bit_count] <= sda_in;

                if (bit_count != 3'd0)
                begin
                  bit_count <= bit_count - 3'd1;
                  phase     <= 2'd0;
                end
                else
                begin
                  phase <= 2'd0;
                  state <= ST_ACK;
                end
              end
            endcase
          end

          ST_ACK:
          begin
            case (phase)
              2'd0:
              begin
                scl_out <= 1'b0;
                sda_oe  <= do_read ? ~do_nack : 1'b0; // read: ACK low unless NACK
                phase   <= 2'd1;
              end

              2'd1:
              begin
                scl_out <= 1'b1;
                if (!do_read && sda_in)
                  ack_error <= 1'b1;
                phase <= 2'd2;
              end

              default:
              begin
                scl_out <= 1'b0;
                sda_oe  <= 1'b0;
                phase   <= 2'd0;

                if (do_read)
                begin
                  rx_data  <= shift;
                  rx_valid <= 1'b1;
                end

                if (do_stop)
                begin
                  state  <= ST_STOP;
                  sda_oe <= 1'b1;
                end
                else
                begin
                  busy  <= 1'b0;
                  done  <= 1'b1;
                  state <= ST_IDLE;
                end
              end
            endcase
          end

          ST_STOP:
          begin
            case (phase)
              2'd0:
              begin
                scl_out <= 1'b0;
                sda_oe  <= 1'b1;
                phase   <= 2'd1;
              end

              2'd1:
              begin
                scl_out <= 1'b1;
                sda_oe  <= 1'b1;
                phase   <= 2'd2;
              end

              default:
              begin
                scl_out    <= 1'b1;
                sda_oe     <= 1'b0;   // SDA rising while SCL high
                bus_active <= 1'b0;
                busy       <= 1'b0;
                done       <= 1'b1;
                state      <= ST_IDLE;
                phase      <= 2'd0;
              end
            endcase
          end

          default:
          begin
            busy       <= 1'b0;
            bus_active <= 1'b0;
            state      <= ST_IDLE;
            scl_out    <= 1'b1;
            sda_oe     <= 1'b0;
            done       <= 1'b1;
            ack_error  <= 1'b1;
          end
        endcase
      end
    end
  end

  always @(*)
  begin
    cpu_dout = 16'd0;

    case (reg_addr)
      4'h0:
      begin
        cpu_dout[0] = enable;
        cpu_dout[1] = irq_enable;
      end

      4'h1:
      begin
        cpu_dout[0] = busy;
        cpu_dout[1] = bus_active;
        cpu_dout[2] = done;
        cpu_dout[3] = ack_error;
        cpu_dout[4] = rx_valid;
        cpu_dout[5] = done;       // minimal replacement for old irq_pending
      end

      4'h2:
      begin
        cpu_dout[7:0] = I2C_DIV;
      end

      4'h3:
      begin
        cpu_dout[7:0] = rx_data;
      end
    endcase
  end

endmodule

// Debugger's communicator.
// RX protocol, MSB first:
//   8'hA5 sync + 4-bit cmd + 4-bit addr + 16-bit data = 32 clocks
// The RX side uses a sliding 32-bit window. If one clock is missed or extra,
// it automatically locks again when the next 8'hA5 header appears.
// and after that TX Message is
// 16-bit data, MSB first, on the next 16 dbg_clk falling edges.
//  if it is accepted, the data is 0xACCE.
//  If it is a read command, the data is the register value.
//  If it is a ping command, the data is 0xDB12. Otherwise,
//  the data is 0xEEEE to indicate an error.
module debug_serial_frontend
(
    input  wire        cpu_clk,
    input  wire        rst_n,

    input  wire        dbg_clk,
    input  wire        dbg_data_in,
    output reg         dbg_data_out,
    output reg         dbg_data_oe,

    output reg         reg_wr,
    output reg  [3:0]  reg_addr,
    output reg  [15:0] reg_wdata,
    input  wire [15:0] reg_rdata
);
    localparam S_RX        = 3'd0;
    localparam S_EXEC      = 3'd1;
    localparam S_LOAD_TX   = 3'd2;
    localparam S_TURNAROUND= 3'd3;
    localparam S_TX        = 3'd4;

    localparam SYNC_BYTE  = 8'hA5;

    localparam CMD_PING  = 4'h0;
    localparam CMD_READ  = 4'h1;
    localparam CMD_WRITE = 4'h2;

    reg [2:0]  state;

    reg [2:0]  dbg_clk_sync;
    reg [1:0]  dbg_data_sync;

    wire dbg_clk_rise;
    wire dbg_clk_fall;

    assign dbg_clk_rise = (dbg_clk_sync[2:1] == 2'b01);
    assign dbg_clk_fall = (dbg_clk_sync[2:1] == 2'b10);

    reg [31:0] rx_shift;
    wire [31:0] rx_next;
    wire        rx_next_cmd_valid;
    wire        rx_next_is_frame;

    assign rx_next = {rx_shift[30:0], dbg_data_sync[1]};
    assign rx_next_cmd_valid = (rx_next[23:20] == CMD_PING)  |
                               (rx_next[23:20] == CMD_READ)  |
                               (rx_next[23:20] == CMD_WRITE);
    assign rx_next_is_frame = (rx_next[31:24] == SYNC_BYTE) & rx_next_cmd_valid;

    reg [3:0]  cmd_latched;
    reg [3:0]  addr_latched;
    reg [15:0] data_latched;

    reg [15:0] tx_shift;
    reg [4:0]  tx_count;

    always @(posedge cpu_clk or negedge rst_n) begin
        if (!rst_n) begin
            state        <= S_RX;
            dbg_clk_sync <= 3'b000;
            dbg_data_sync<= 2'b11;
            dbg_data_out <= 1'b1;
            dbg_data_oe  <= 1'b0;
            reg_wr       <= 1'b0;
            reg_addr     <= 4'h0;
            reg_wdata    <= 16'h0000;
            rx_shift     <= 32'h00000000;
            cmd_latched  <= 4'h0;
            addr_latched <= 4'h0;
            data_latched <= 16'h0000;
            tx_shift     <= 16'h0000;
            tx_count     <= 5'd0;
        end else begin
            dbg_clk_sync  <= {dbg_clk_sync[1:0], dbg_clk};
            dbg_data_sync <= {dbg_data_sync[0], dbg_data_in};
            reg_wr <= 1'b0;

            case (state)
                S_RX: begin
                    dbg_data_oe  <= 1'b0;
                    dbg_data_out <= 1'b1;

                    if (dbg_clk_rise) begin
                        if (rx_next_is_frame) begin
                            cmd_latched  <= rx_next[23:20];
                            addr_latched <= rx_next[19:16];
                            data_latched <= rx_next[15:0];
                            rx_shift     <= 32'h00000000;
                            state        <= S_EXEC;
                        end else begin
                            rx_shift <= rx_next;
                        end
                    end
                end

                S_EXEC: begin
                    reg_addr  <= addr_latched;
                    reg_wdata <= data_latched;
                    if (cmd_latched == CMD_WRITE)
                        reg_wr <= 1'b1;
                    state <= S_LOAD_TX;
                end

                S_LOAD_TX: begin
                    if (cmd_latched == CMD_PING)
                        tx_shift <= 16'hDB12;
                    else if (cmd_latched == CMD_READ)
                        tx_shift <= reg_rdata;
                    else if (cmd_latched == CMD_WRITE)
                        tx_shift <= 16'hACCE;
                    else
                        tx_shift <= 16'hEEEE;

                    tx_count     <= 5'd0;
                    dbg_data_oe  <= 1'b0;
                    dbg_data_out <= 1'b1;
                    state        <= S_TURNAROUND;
                end

                S_TURNAROUND: begin
                    dbg_data_oe <= 1'b0;
                    if (dbg_clk_fall) begin
                        dbg_data_oe  <= 1'b1;
                        dbg_data_out <= tx_shift[15];
                        state        <= S_TX;
                    end
                end

                S_TX: begin
                    if (dbg_clk_fall) begin
                        if (tx_count == 5'd15) begin
                            dbg_data_oe  <= 1'b0;
                            dbg_data_out <= 1'b1;
                            rx_shift     <= 32'h00000000;
                            state        <= S_RX;
                        end else begin
                            tx_shift     <= {tx_shift[14:0], 1'b0};
                            dbg_data_out <= tx_shift[14];
                            tx_count     <= tx_count + 5'd1;
                        end
                    end
                end

                default: begin
                    state        <= S_RX;
                    dbg_data_oe  <= 1'b0;
                    dbg_data_out <= 1'b1;
                    rx_shift     <= 32'h00000000;
                end
            endcase
        end
    end

endmodule

// this module controlles the execute timing of the CPU.
// The debugger can interface with this module to alter the execution flow (halt, step, etc).
// if a data needs to be loaded or stored, the controller will wait for the data_done signal 
// before proceeding to the next instruction fetch.

module cpu_cycle_controller
(
    input  wire clk,
    input  wire rst_n,

    input  wire fetch_done,
    input  wire data_done,

    input  wire ld,
    input  wire st,
    input  wire flash_ld,

    input  wire dbg_enable,
    input  wire dbg_halt_req,
    input  wire dbg_run_req,
    input  wire dbg_step_req,
    input  wire dbg_break_hit,
    input  wire dbg_break_after_exec,

    output wire fetch_req,
    output wire execute_now_pulse,
    output wire dbg_halted
);

  localparam S_REQ_FETCH  = 3'd0;
  localparam S_WAIT_FETCH = 3'd1;
  localparam S_EXECUTE    = 3'd2;
  localparam S_WAIT_DATA  = 3'd3;
  localparam S_HALTED     = 3'd4;

  reg [2:0] state;
  reg       step_active;

  wire mem_op;
  wire stop_after_exec;

  assign mem_op            = ld | st | flash_ld;
  assign fetch_req         = (state == S_REQ_FETCH);
  assign execute_now_pulse = (state == S_EXECUTE);
  assign dbg_halted        = (state == S_HALTED);
  assign stop_after_exec   = dbg_enable & (dbg_halt_req | step_active | dbg_break_after_exec);

  always @(posedge clk or negedge rst_n)
  begin
    if (!rst_n)
    begin
      state       <= S_REQ_FETCH;
      step_active <= 1'b0;
    end
    else if (!dbg_enable)
    begin
      step_active <= 1'b0;

      case (state)
        S_REQ_FETCH:  state <= S_WAIT_FETCH;
        S_WAIT_FETCH: if (fetch_done) state <= S_EXECUTE;
        S_EXECUTE:    state <= mem_op ? S_WAIT_DATA : S_REQ_FETCH;
        S_WAIT_DATA:  if (data_done) state <= S_REQ_FETCH;
        default:      state <= S_REQ_FETCH;
      endcase
    end
    else
    begin
      case (state)
        S_REQ_FETCH:
        begin
          if (dbg_halt_req)
          begin
            state       <= S_HALTED;
            step_active <= 1'b0;
          end
          else
            state <= S_WAIT_FETCH;
        end

        S_WAIT_FETCH:
        begin
          if (fetch_done)
          begin
            if (dbg_break_hit | dbg_halt_req)
            begin
              state       <= S_HALTED;
              step_active <= 1'b0;
            end
            else
              state <= S_EXECUTE;
          end
        end

        S_EXECUTE:
        begin
          if (mem_op)
            state <= S_WAIT_DATA;
          else if (stop_after_exec)
          begin
            state       <= S_HALTED;
            step_active <= 1'b0;
          end
          else
            state <= S_REQ_FETCH;
        end

        S_WAIT_DATA:
        begin
          if (data_done)
          begin
            if (stop_after_exec)
            begin
              state       <= S_HALTED;
              step_active <= 1'b0;
            end
            else
              state <= S_REQ_FETCH;
          end
        end

        S_HALTED:
        begin
          if (dbg_run_req)
          begin
            state       <= S_REQ_FETCH;
            step_active <= 1'b0;
          end
          else if (dbg_step_req)
          begin
            state       <= S_REQ_FETCH;
            step_active <= 1'b1;
          end
        end

        default:
        begin
          state       <= S_REQ_FETCH;
          step_active <= 1'b0;
        end
      endcase
    end
  end

endmodule

// this module controls the flow of memory access.
// So either instruction fetch or data load/store, the CPU will wait for this controller to assert the done signal 
//before proceeding to the next step.
// Wtih this core it is also possible to read from program memory and then store it into tthe registers.

module memory_wait_controller
(
    input  wire        clk,
    input  wire        rst_n,

    input  wire        fetch_req,
    input  wire        ld_req,
    input  wire        st_req,
    input  wire        flash_req,

    input  wire [15:0] fetch_addr,
    input  wire [15:0] data_addr,
    input  wire [15:0] store_data,

    output reg  [15:0] mem_rdata,
    output reg         fetch_done,
    output reg         data_done,
    output reg         mem_stall,

    output reg         spi_st,
    output reg         spi_ld,
    output reg  [15:0] spi_addr,
    output reg  [15:0] spi_data_in,
    output reg         spi_target,
    input  wire [15:0] spi_data_out,
    input  wire        spi_busy
);

  localparam OP_NONE  = 2'd0;
  localparam OP_FETCH = 2'd1;
  localparam OP_LOAD  = 2'd2;
  localparam OP_STORE = 2'd3;

  localparam S_IDLE           = 3'd0;
  localparam S_START          = 3'd1;
  localparam S_WAIT_BUSY_HIGH = 3'd2;
  localparam S_WAIT_BUSY_LOW  = 3'd3;
  localparam S_FINISH         = 3'd4;

  reg [2:0] state;
  reg [1:0] op;


  always @(posedge clk or negedge rst_n)
  begin
    if (!rst_n)
    begin
      state              <= S_IDLE;
      op                 <= OP_NONE;
      mem_rdata          <= 16'h0000;
      fetch_done         <= 1'b0;
      data_done          <= 1'b0;
      mem_stall          <= 1'b0;
      spi_st             <= 1'b0;
      spi_ld             <= 1'b0;
      spi_addr           <= 16'h0000;
      spi_data_in        <= 16'h0000;
      spi_target         <= 1'b0;
    end
    else
    begin
      fetch_done <= 1'b0;
      data_done  <= 1'b0;
      spi_st     <= 1'b0;
      spi_ld     <= 1'b0;

      case (state)
        S_IDLE:
        begin
          mem_stall <= 1'b0;
          op        <= OP_NONE;

          if (st_req)
          begin
            op          <= OP_STORE;
            spi_target  <= 1'b1;
            spi_addr    <= data_addr;
            spi_data_in <= store_data;
            mem_stall   <= 1'b1;
            state       <= S_START;
          end
          else if (ld_req)
          begin
            op          <= OP_LOAD;
            spi_target  <= 1'b1;
            spi_addr    <= data_addr;
            spi_data_in <= 16'h0000;
            mem_stall   <= 1'b1;
            state       <= S_START;
          end
          else if (fetch_req)
          begin
            op          <= OP_FETCH;
            spi_target  <= 1'b0;
            spi_addr    <= fetch_addr;
            spi_data_in <= 16'h0000;
            mem_stall   <= 1'b1;
            state       <= S_START;
          end
          else if (flash_req)
          begin
            op          <= OP_LOAD;
            spi_target  <= 1'b0;
            spi_addr    <= data_addr;
            spi_data_in <= 16'h0000;
            mem_stall   <= 1'b1;
            state       <= S_START;
          end
        end

        S_START:
        begin
          if (op == OP_STORE)
            spi_st <= 1'b1;
          else
          begin
            spi_ld <= 1'b1;
            
          end
          state <= S_WAIT_BUSY_HIGH;
        end

        S_WAIT_BUSY_HIGH:
          if (spi_busy)
            state <= S_WAIT_BUSY_LOW;

        S_WAIT_BUSY_LOW:
        begin
          if (!spi_busy)
          begin
            if (op != OP_STORE)
              mem_rdata <= spi_data_out;
            state <= S_FINISH;
          end
        end

        S_FINISH:
        begin
          mem_stall <= 1'b0;
          if (op == OP_FETCH)
          begin
            fetch_done         <= 1'b1;
          end
          else
          begin
            data_done          <= 1'b1;
          end
          state <= S_IDLE;
        end

        default:
        begin
          state              <= S_IDLE;
        end
      endcase
    end
  end

endmodule

// Debugger's core logic.
// it can
// - set breakpoint(only 1 at the moment)
// - halt and run the CPU
// - single step the CPU
// - load a new PC value into the CPU to jump to an arbitrary location (useful for stepping through reset/startup code that is not easily reachable with a breakpoint)
// - static break on BRK instruction (compiled into the code) (useful for catching infinite loops in startup code)
// It also provides a register interface for the debugger to read CPU status and control the debug features.
// - Program counter, instruction register, and flags are readable for debugging purposes.
//
module debug_core
  (
    input  wire        clk,
    input  wire        rst_n,

    // Register port
    input  wire        reg_wr,
    input  wire [3:0]  reg_addr,
    input  wire [15:0] reg_wdata,
    output reg  [15:0] reg_rdata,

    // CPU status
    input  wire        cpu_dbg_halted,
    input  wire [2:0]  cpu_flags,
    input  wire [15:0] cpu_pc,
    input  wire [15:0] cpu_ir,
    input  wire        instr_is_brk,
    input  wire        execute_now_pulse,

    // Debug control outputs
    output reg         dbg_enable,
    output reg         dbg_halt_req,
    output reg         dbg_run_req,
    output reg         dbg_step_req,
    output reg         static_break_enable,

    output wire        dbg_break_hit,
    output wire        dbg_break_after_exec,

    // Debug load-PC request.
    // dbg_jump_req is sticky and stays high until dbg_jump_ack is seen.
    output reg         dbg_jump_req,
    output reg  [15:0] dbg_jump_addr,
    input  wire        dbg_jump_ack
  );

  localparam REG_ID        = 4'h0;
  localparam REG_STATUS    = 4'h1;
  localparam REG_CONTROL   = 4'h2;
  localparam REG_FLAGS     = 4'h3;
  localparam REG_PC        = 4'h4;
  localparam REG_IR        = 4'h5;
  localparam REG_BP0       = 4'h6;
  localparam REG_BPCTRL    = 4'h7;
  localparam REG_JUMP_ADDR = 4'h8;

  // REG_CONTROL bits, write side:
  //   bit0 = debug enable level
  //   bit1 = halt request level/set
  //   bit2 = run pulse
  //   bit3 = step pulse
  //   bit4 = reserved
  //   bit5 = static BRK enable level
  //   bit6 = jump/load-PC request using REG_JUMP_ADDR

  // One dynamic breakpoint only sadly
  reg  [15:0] bp0;
  reg         bp_enable;
  reg         bp_resume_mask;
  wire        resume_cmd;
  wire        bp_raw_hit;

  assign resume_cmd = dbg_run_req | dbg_step_req;
  assign bp_raw_hit = dbg_enable & bp_enable & (cpu_pc == bp0);

  assign dbg_break_hit        = bp_raw_hit & ~bp_resume_mask;
  assign dbg_break_after_exec = dbg_enable & static_break_enable & instr_is_brk;

  always @(posedge clk or negedge rst_n)
  begin
    if (!rst_n)
    begin
      dbg_enable           <= 1'b0;
      dbg_halt_req         <= 1'b0;
      dbg_run_req          <= 1'b0;
      dbg_step_req         <= 1'b0;
      static_break_enable  <= 1'b0;
      dbg_jump_req         <= 1'b0;
      dbg_jump_addr        <= 16'h0000;
      bp0                  <= 16'h0000;
      bp_enable            <= 1'b0;
    end
    else
    begin
      dbg_run_req  <= 1'b0;
      dbg_step_req <= 1'b0;
      if (dbg_jump_ack)
        dbg_jump_req <= 1'b0;

      if (cpu_dbg_halted)
        dbg_halt_req <= 1'b0;

      if (reg_wr)
      begin
        case (reg_addr)
          REG_CONTROL:
          begin
            dbg_enable          <= reg_wdata[0];
            static_break_enable <= reg_wdata[5];

            if (!reg_wdata[0])
            begin
              dbg_halt_req <= 1'b0;
              dbg_jump_req <= 1'b0;
            end

            if (reg_wdata[1] && reg_wdata[0])
              dbg_halt_req <= 1'b1;

            if (reg_wdata[2] && reg_wdata[0])
            begin
              dbg_run_req  <= 1'b1;
              dbg_halt_req <= 1'b0;
            end

            if (reg_wdata[3] && reg_wdata[0])
            begin
              dbg_step_req <= 1'b1;
              dbg_halt_req <= 1'b0;
            end

            if (reg_wdata[6] && reg_wdata[0])
              dbg_jump_req <= 1'b1;
          end

          REG_BP0:
            bp0 <= reg_wdata;

          REG_BPCTRL:
            bp_enable <= reg_wdata[0];

          REG_JUMP_ADDR:
            dbg_jump_addr <= reg_wdata;

          default:
          begin
          end
        endcase
      end
    end
  end

  always @(*)
  begin
    case (reg_addr)
      REG_ID:
        reg_rdata = 16'hDB11;

      REG_STATUS:
        reg_rdata = {
          8'h00,
          bp_resume_mask,
          bp_enable,
          static_break_enable,
          dbg_enable,
          cpu_dbg_halted,
          1'b0,          // reserved
          dbg_jump_req,  // pending jump/load-PC request
          dbg_halt_req
        };

      REG_CONTROL:
        reg_rdata = {
          9'h000,
          dbg_jump_req,          // bit6: pending jump state
          static_break_enable,   // bit5
          1'b0,                  // bit4 reserved
          1'b0,                  // bit3 step is write-only pulse
          1'b0,                  // bit2 run is write-only pulse
          dbg_halt_req,          // bit1
          dbg_enable             // bit0
        };

      REG_FLAGS:
        reg_rdata = {13'h0000, cpu_flags};

      REG_PC:
        reg_rdata = cpu_pc;

      REG_IR:
        reg_rdata = cpu_ir;

      REG_BP0:
        reg_rdata = bp0;

      REG_BPCTRL:
        reg_rdata = {15'h0000, bp_enable};

      REG_JUMP_ADDR:
        reg_rdata = dbg_jump_addr;

      default:
        reg_rdata = 16'h0000;
    endcase
  end

  always @(posedge clk or negedge rst_n)
  begin
    if (!rst_n)
      bp_resume_mask <= 1'b0;
    else if (execute_now_pulse)
      bp_resume_mask <= 1'b0;
    else if (cpu_dbg_halted & resume_cmd)
      bp_resume_mask <= 1'b1;
  end

endmodule

// Flat / no-instantiation memory interface.
// Area-focused version: Flash = QSPI continuous read, RAM = plain SPI read/write.
//
// Main area reductions versus initwait version:
//   - no 24-bit runtime address shift register
//   - no 16-bit runtime write-data shift register
//   - no 8-bit RAM command shift register
//   - no 8-bit flash mode shift register
//   - smaller state/counter registers
//   - smaller init wait counter for 50 MHz / 40 ms max default wait
//   - RAM reset/init removed to save area; RAM CS stays high during init
//
// CPU side:
//   spi_target = 0 -> Flash read only, byte address {7'b0, addr, 1'b0}
//   spi_target = 1 -> RAM read/write, byte address {1'b0, 6'b0, addr, 1'b0}
//
// External bus pins:
//   Flash QSPI uses IO[3:0].
//   RAM SPI uses IO0 = MOSI and IO1 = MISO. IO2/IO3 are released for RAM.
// 

module qspi_memory_interface (
    input  wire        clk,
    input  wire        spi_rst_n,

    input  wire        st,
    input  wire        ld,
    input  wire        spi_target,    // 0 = flash, 1 = RAM
    input  wire [15:0] addr,
    input  wire [15:0] data_in,
    output reg  [15:0] data_out,

    output wire        spi_clk,
    output wire        spi_flash_cs,  // active low
    output wire        spi_ram_cs,    // active low

    input  wire [3:0]  spi_data_in,
    output wire [3:0]  spi_data_out,
    output wire [3:0]  spi_data_oe,

    output reg         busy
);

// ============================================================
// 0) Shared output mux: init owns pins until init_done = 1
// ============================================================

    wire init_done;

    reg        init_spi_clk;
    reg        init_flash_cs;
    reg        init_ram_cs;
    reg [3:0]  init_data_out;
    reg [3:0]  init_data_oe;

    reg        core_spi_clk;
    reg        core_flash_cs;
    reg        core_ram_cs;
    reg [3:0]  core_data_out;
    reg [3:0]  core_data_oe;

    assign spi_clk      = init_done ? core_spi_clk   : init_spi_clk;
    assign spi_flash_cs = init_done ? core_flash_cs  : init_flash_cs;
    assign spi_ram_cs   = init_done ? core_ram_cs    : init_ram_cs;
    assign spi_data_out = init_done ? core_data_out  : init_data_out;
    assign spi_data_oe  = init_done ? core_data_oe   : init_data_oe;

// ============================================================
// 1) CPU 16-bit word wrapper FSM
// ============================================================

    localparam W_IDLE       = 2'd0;
    localparam W_START      = 2'd1;
    localparam W_WAIT_BUSY  = 2'd2;
    localparam W_WAIT_IDLE  = 2'd3;

    reg [1:0]  wstate;
    reg        op_is_read;
    reg [15:0] core_addr_cpu;
    reg [15:0] core_write_word;
    reg        core_start_read;
    reg        core_start_write;
    reg        core_target_ram;

    wire [15:0] core_read_word;
    wire        core_busy;

    always @(posedge clk or negedge spi_rst_n) begin
        if (!spi_rst_n) begin
            wstate           <= W_IDLE;
            busy             <= 1'b0;
            op_is_read       <= 1'b0;
            core_addr_cpu    <= 16'h0000;
            core_write_word  <= 16'h0000;
            core_start_read  <= 1'b0;
            core_start_write <= 1'b0;
            core_target_ram  <= 1'b0;
            data_out         <= 16'h0000;
        end else begin
            core_start_read  <= 1'b0;
            core_start_write <= 1'b0;

            case (wstate)
                W_IDLE: begin
                    busy <= !init_done;

                    if (!init_done) begin
                        wstate <= W_IDLE;
                    end else if (ld) begin
                        busy            <= 1'b1;
                        op_is_read      <= 1'b1;
                        core_target_ram <= spi_target;
                        core_addr_cpu   <= addr;
                        wstate          <= W_START;
                    end else if (st) begin
                        // Flash writing is intentionally blocked here.
                        // RAM writes are SPI only.
                        if (spi_target) begin
                            busy             <= 1'b1;
                            op_is_read       <= 1'b0;
                            core_target_ram  <= 1'b1;
                            core_addr_cpu    <= addr;
                            core_write_word  <= data_in;
                            wstate           <= W_START;
                        end else begin
                            busy   <= 1'b0;
                            wstate <= W_IDLE;
                        end
                    end
                end

                W_START: begin
                    busy <= 1'b1;
                    if (op_is_read)
                        core_start_read <= 1'b1;
                    else
                        core_start_write <= 1'b1;
                    wstate <= W_WAIT_BUSY;
                end

                W_WAIT_BUSY: begin
                    busy <= 1'b1;
                    if (core_busy)
                        wstate <= W_WAIT_IDLE;
                end

                W_WAIT_IDLE: begin
                    if (!core_busy) begin
                        if (op_is_read)
                            data_out <= core_read_word;
                        busy       <= 1'b0;
                        op_is_read <= 1'b0;
                        wstate     <= W_IDLE;
                    end else begin
                        busy <= 1'b1;
                    end
                end
            endcase
        end
    end

// ============================================================
// 2) Startup initializer FSM
// ============================================================

    localparam I_IDLE       = 3'd0;
    localparam I_WAIT_PWR   = 3'd1;
    localparam I_LOAD       = 3'd2;
    localparam I_SHIFT_LOW  = 3'd3;
    localparam I_SHIFT_HIGH = 3'd4;
    localparam I_CS_HIGH    = 3'd5;
    localparam I_GAP        = 3'd6;
    localparam I_DONE       = 3'd7;

    localparam INIT_STEP_FLASH_RST_EN = 4'd0;
    localparam INIT_STEP_FLASH_RST    = 4'd1;
    localparam INIT_STEP_FLASH_WREN   = 4'd2;
    localparam INIT_STEP_FLASH_SR2    = 4'd3;
    localparam INIT_STEP_FLASH_EB     = 4'd4;
    localparam INIT_STEP_FLASH_CONT   = 4'd5;
    localparam INIT_STEP_END          = 4'd6;

    // Default waits fit in 22 bits at 50 MHz:
    // 40 ms = 2,000,000 cycles. If you increase INIT_CLK_HZ a lot,
    // increase INIT_WAIT_BITS too.
    localparam integer INIT_CLK_HZ      = 50000000;
    localparam integer INIT_WAIT_BITS   = 22;
`ifdef COCOTB_SIM_FAST_INIT
    localparam [INIT_WAIT_BITS-1:0] INIT_POWER_WAIT_CYCLES      = 22'd82;
    localparam [INIT_WAIT_BITS-1:0] INIT_RESET_WAIT_CYCLES      = 22'd82;
    localparam [INIT_WAIT_BITS-1:0] INIT_FLASH_SR2_WAIT_CYCLES  = 22'd82;
    localparam [INIT_WAIT_BITS-1:0] INIT_FLASH_CONT_WAIT_CYCLES = 22'd82;
    localparam [INIT_WAIT_BITS-1:0] INIT_CMD_GAP_CYCLES         = 22'd82;
`else
    localparam [INIT_WAIT_BITS-1:0] INIT_POWER_WAIT_CYCLES      = (INIT_CLK_HZ / 1000) * 10;
    localparam [INIT_WAIT_BITS-1:0] INIT_RESET_WAIT_CYCLES      = (INIT_CLK_HZ / 1000) * 2;
    localparam [INIT_WAIT_BITS-1:0] INIT_FLASH_SR2_WAIT_CYCLES  = (INIT_CLK_HZ / 1000) * 40;
    localparam [INIT_WAIT_BITS-1:0] INIT_FLASH_CONT_WAIT_CYCLES = (INIT_CLK_HZ / 1000) * 1;
    localparam [INIT_WAIT_BITS-1:0] INIT_CMD_GAP_CYCLES         = (INIT_CLK_HZ / 1000000) * 5 + 4;
`endif

    function [INIT_WAIT_BITS-1:0] init_gap_cycles;
        input [3:0] stp;
        begin
            case (stp)
                INIT_STEP_FLASH_RST:  init_gap_cycles = INIT_RESET_WAIT_CYCLES;
                INIT_STEP_FLASH_SR2:  init_gap_cycles = INIT_FLASH_SR2_WAIT_CYCLES;
                INIT_STEP_FLASH_CONT: init_gap_cycles = INIT_FLASH_CONT_WAIT_CYCLES;
                default:              init_gap_cycles = INIT_CMD_GAP_CYCLES;
            endcase
        end
    endfunction

    function [2:0] init_bytes_left;
        input [3:0] stp;
        begin
            case (stp)
                INIT_STEP_FLASH_SR2:  init_bytes_left = 3'd2;
                INIT_STEP_FLASH_CONT: init_bytes_left = 3'd6;
                INIT_STEP_END:        init_bytes_left = 3'd0;
                default:              init_bytes_left = 3'd1;
            endcase
        end
    endfunction

    function [7:0] init_byte;
        input [3:0] stp;
        input [2:0] idx;
        begin
            case (stp)
                INIT_STEP_FLASH_RST_EN: init_byte = 8'h66;
                INIT_STEP_FLASH_RST:    init_byte = 8'h99;
                INIT_STEP_FLASH_WREN:   init_byte = 8'h06;
                INIT_STEP_FLASH_SR2:    init_byte = (idx == 3'd0) ? 8'h31 : 8'h02;
                INIT_STEP_FLASH_EB:     init_byte = 8'hEB;
                INIT_STEP_FLASH_CONT: begin
                    case (idx)
                        3'd0: init_byte = 8'h00; // addr[23:16]
                        3'd1: init_byte = 8'h00; // addr[15:8]
                        3'd2: init_byte = 8'h00; // addr[7:0]
                        3'd3: init_byte = 8'hA0; // continuous-read mode bits
                        default: init_byte = 8'h00; // dummy clocks
                    endcase
                end
                default: init_byte = 8'h00;
            endcase
        end
    endfunction

    reg [2:0]  init_state;
    reg [3:0]  init_step;
    reg [7:0]  init_shift;
    reg [2:0]  init_bit_cnt;
    reg [INIT_WAIT_BITS-1:0] init_wait_cnt;
    reg [2:0]  init_byte_idx;
    reg        init_done_r;

    wire       init_use_quad_w   = (init_step == INIT_STEP_FLASH_CONT);
    wire [2:0] init_bytes_left_w = init_bytes_left(init_step);

    assign init_done = init_done_r;

    always @(posedge clk or negedge spi_rst_n) begin
        if (!spi_rst_n) begin
            init_state    <= I_IDLE;
            init_step     <= INIT_STEP_FLASH_RST_EN;
            init_done_r   <= 1'b0;
            init_spi_clk  <= 1'b0;
            init_flash_cs <= 1'b1;
            init_ram_cs   <= 1'b1;
            init_data_out <= 4'b0000;
            init_data_oe  <= 4'b0000;
            init_shift    <= 8'h00;
            init_bit_cnt  <= 3'd0;
            init_wait_cnt <= {INIT_WAIT_BITS{1'b0}};
            init_byte_idx <= 3'd0;
        end else begin
            case (init_state)
                I_IDLE: begin
                    init_done_r   <= 1'b0;
                    init_spi_clk  <= 1'b0;
                    init_flash_cs <= 1'b1;
                    init_ram_cs   <= 1'b1;
                    init_data_oe  <= 4'b0000;
                    init_wait_cnt <= INIT_POWER_WAIT_CYCLES;
                    init_state    <= I_WAIT_PWR;
                end

                I_WAIT_PWR: begin
                    if (init_wait_cnt != {INIT_WAIT_BITS{1'b0}})
                        init_wait_cnt <= init_wait_cnt - {{(INIT_WAIT_BITS-1){1'b0}}, 1'b1};
                    else
                        init_state <= I_LOAD;
                end

                I_LOAD: begin
                    if (init_step >= INIT_STEP_END) begin
                        init_state <= I_DONE;
                    end else begin
                        init_spi_clk  <= 1'b0;
                        init_flash_cs <= 1'b0;
                        init_ram_cs   <= 1'b1;
                        init_byte_idx <= 3'd0;
                        init_shift    <= init_byte(init_step, 3'd0);
                        init_bit_cnt  <= init_use_quad_w ? 3'd1 : 3'd7;
                        init_state    <= I_SHIFT_LOW;
                    end
                end

                I_SHIFT_LOW: begin
                    init_spi_clk <= 1'b0;
                    if (init_use_quad_w) begin
                        init_data_oe  <= 4'b1111;
                        init_data_out <= init_shift[7:4];
                    end else begin
                        // SPI command: IO0 = MOSI, IO1 = MISO released.
                        init_data_oe  <= 4'b0001;
                        init_data_out <= {3'b000, init_shift[7]};
                    end
                    init_state <= I_SHIFT_HIGH;
                end

                I_SHIFT_HIGH: begin
                    init_spi_clk <= 1'b1;
                    if (init_bit_cnt == 3'd0) begin
                        if (init_byte_idx + 3'd1 >= init_bytes_left_w) begin
                            init_state <= I_CS_HIGH;
                        end else begin
                            init_byte_idx <= init_byte_idx + 3'd1;
                            init_shift    <= init_byte(init_step, init_byte_idx + 3'd1);
                            init_bit_cnt  <= init_use_quad_w ? 3'd1 : 3'd7;
                            init_state    <= I_SHIFT_LOW;
                        end
                    end else begin
                        if (init_use_quad_w)
                            init_shift <= {init_shift[3:0], 4'h0};
                        else
                            init_shift <= {init_shift[6:0], 1'b0};
                        init_bit_cnt <= init_bit_cnt - 3'd1;
                        init_state   <= I_SHIFT_LOW;
                    end
                end

                I_CS_HIGH: begin
                    init_spi_clk <= 1'b0;
                    init_data_oe <= 4'b0000;

                    // Keep flash CS low between EBh command and the quad address/mode/dummy part.
                    if (init_step == INIT_STEP_FLASH_EB) begin
                        init_flash_cs <= 1'b0;
                        init_ram_cs   <= 1'b1;
                        init_step     <= INIT_STEP_FLASH_CONT;
                        init_state    <= I_LOAD;
                    end else begin
                        init_flash_cs <= 1'b1;
                        init_ram_cs   <= 1'b1;
                        init_wait_cnt <= init_gap_cycles(init_step);
                        init_state    <= I_GAP;
                    end
                end

                I_GAP: begin
                    if (init_wait_cnt != {INIT_WAIT_BITS{1'b0}})
                        init_wait_cnt <= init_wait_cnt - {{(INIT_WAIT_BITS-1){1'b0}}, 1'b1};
                    else begin
                        init_step  <= init_step + 4'd1;
                        init_state <= I_LOAD;
                    end
                end

                I_DONE: begin
                    init_done_r   <= 1'b1;
                    init_spi_clk  <= 1'b0;
                    init_flash_cs <= 1'b1;
                    init_ram_cs   <= 1'b1;
                    init_data_oe  <= 4'b0000;
                end
            endcase
        end
    end

// ============================================================
// 3) Runtime memory core
// ============================================================

    localparam C_IDLE        = 4'd0;
    localparam C_FLASH_ADDR  = 4'd1;
    localparam C_FLASH_MODE  = 4'd2;
    localparam C_FLASH_DUMMY = 4'd3;
    localparam C_FLASH_DATA  = 4'd4;
    localparam C_RAM_CMD     = 4'd5;
    localparam C_RAM_ADDR    = 4'd6;
    localparam C_RAM_DATA    = 4'd7;
    localparam C_FINISH      = 4'd8;

    reg [3:0]  core_state;
    reg        core_is_writing;
    reg [15:0] core_read_shift;
    reg [4:0]  core_count;
    reg [15:0] core_read_word_r;

    assign core_busy      = (core_state != C_IDLE);
    assign core_read_word = core_read_word_r;

    // Address mapping. CPU address is word address, external memory is byte address.
    wire [23:0] flash_byte_addr = {7'b0000000, core_addr_cpu, 1'b0};
    wire [23:0] ram_byte_addr   = {1'b0, 6'b000000, core_addr_cpu, 1'b0};

    wire ram_cmd_mosi = (core_count == 5'd1) ||
                        ((core_count == 5'd0) && !core_is_writing); // write=02h, read=03h

    always @(posedge clk or negedge spi_rst_n) begin
        if (!spi_rst_n) begin
            core_state       <= C_IDLE;
            core_spi_clk     <= 1'b0;
            core_flash_cs    <= 1'b1;
            core_ram_cs      <= 1'b1;
            core_data_oe     <= 4'b0000;
            core_is_writing  <= 1'b0;
            core_read_shift  <= 16'h0000;
            core_count       <= 5'd0;
            core_read_word_r <= 16'h0000;
        end else if (!init_done) begin
            core_state     <= C_IDLE;
            core_spi_clk   <= 1'b0;
            core_flash_cs  <= 1'b1;
            core_ram_cs    <= 1'b1;
            core_data_oe   <= 4'b0000;
        end else begin
            if (core_state == C_IDLE) begin
                core_spi_clk  <= 1'b0;
                core_data_oe  <= 4'b0000;
                core_flash_cs <= 1'b1;
                core_ram_cs   <= 1'b1;

                if (core_start_read || core_start_write) begin
                    core_is_writing <= core_start_write;
                    core_read_shift <= 16'h0000;

                    if (core_target_ram) begin
                        // RAM stays plain SPI.
                        core_flash_cs <= 1'b1;
                        core_ram_cs   <= 1'b0;
                        core_data_oe  <= 4'b0001; // IO0 MOSI only
                        core_count    <= 5'd7;    // 8 SPI command bits
                        core_state    <= C_RAM_CMD;
                    end else begin
                        // Flash is already in continuous QSPI read mode.
                        core_flash_cs <= 1'b0;
                        core_ram_cs   <= 1'b1;
                        core_data_oe  <= 4'b1111;
                        core_count    <= 5'd5; // 6 QSPI address nibbles
                        core_state    <= C_FLASH_ADDR;
                    end
                end
            end else if (core_state == C_FINISH) begin
                // Hold CS low for one extra system clock with SCK low, then release.
                core_spi_clk    <= 1'b0;
                core_data_oe    <= 4'b0000;
                core_flash_cs   <= 1'b1;
                core_ram_cs     <= 1'b1;
                core_is_writing <= 1'b0;
                core_state      <= C_IDLE;
            end else begin
                // Two system clocks per external SPI/QSPI clock.
                core_spi_clk <= !core_spi_clk;

                // Advance/sample on the high phase just before we drive SCK low.
                if (core_spi_clk) begin
                    case (core_state)
                        C_FLASH_ADDR: begin
                            if (core_count == 5'd0) begin
                                core_count <= 5'd1; // 2 QSPI mode nibbles: A,0
                                core_state <= C_FLASH_MODE;
                            end else begin
                                core_count <= core_count - 5'd1;
                            end
                        end

                        C_FLASH_MODE: begin
                            if (core_count == 5'd0) begin
                                core_data_oe <= 4'b0000;
                                core_count   <= 5'd3; // 4 QSPI dummy clocks
                                core_state   <= C_FLASH_DUMMY;
                            end else begin
                                core_count <= core_count - 5'd1;
                            end
                        end

                        C_FLASH_DUMMY: begin
                            if (core_count == 5'd0) begin
                                core_count <= 5'd3; // 4 QSPI data clocks = 16 bits
                                core_state <= C_FLASH_DATA;
                            end else begin
                                core_count <= core_count - 5'd1;
                            end
                        end

                        C_FLASH_DATA: begin
                            core_read_shift <= {core_read_shift[11:0], spi_data_in};
                            if (core_count == 5'd0) begin
                                core_read_word_r <= {core_read_shift[11:0], spi_data_in};
                                core_state       <= C_FINISH;
                            end else begin
                                core_count <= core_count - 5'd1;
                            end
                        end

                        C_RAM_CMD: begin
                            if (core_count == 5'd0) begin
                                core_count <= 5'd23; // 24 SPI address bits
                                core_state <= C_RAM_ADDR;
                            end else begin
                                core_count <= core_count - 5'd1;
                            end
                        end

                        C_RAM_ADDR: begin
                            if (core_count == 5'd0) begin
                                core_count <= 5'd15; // 16 data bits
                                core_state <= C_RAM_DATA;
                                if (core_is_writing)
                                    core_data_oe <= 4'b0001; // keep driving MOSI
                                else
                                    core_data_oe <= 4'b0000; // release bus, RAM drives IO1/MISO
                            end else begin
                                core_count <= core_count - 5'd1;
                            end
                        end

                        C_RAM_DATA: begin
                            if (core_is_writing) begin
                                if (core_count == 5'd0) begin
                                    core_state <= C_FINISH;
                                end else begin
                                    core_count <= core_count - 5'd1;
                                end
                            end else begin
                                core_read_shift <= {core_read_shift[14:0], spi_data_in[1]};
                                if (core_count == 5'd0) begin
                                    core_read_word_r <= {core_read_shift[14:0], spi_data_in[1]};
                                    core_state       <= C_FINISH;
                                end else begin
                                    core_count <= core_count - 5'd1;
                                end
                            end
                        end

                        default: begin
                            core_state <= C_FINISH;
                        end
                    endcase
                end
            end
        end
    end

    always @(*) begin
        core_data_out = 4'b1111;

        case (core_state)
            C_FLASH_ADDR: begin
                case (core_count)
                    5'd5: core_data_out = flash_byte_addr[23:20];
                    5'd4: core_data_out = flash_byte_addr[19:16];
                    5'd3: core_data_out = flash_byte_addr[15:12];
                    5'd2: core_data_out = flash_byte_addr[11:8];
                    5'd1: core_data_out = flash_byte_addr[7:4];
                    default: core_data_out = flash_byte_addr[3:0];
                endcase
            end

            C_FLASH_MODE: begin
                core_data_out = (core_count == 5'd1) ? 4'hA : 4'h0;
            end

            C_FLASH_DUMMY: begin
                core_data_out = 4'b1111;
            end

            C_FLASH_DATA: begin
                core_data_out = 4'b1111;
            end

            C_RAM_CMD: begin
                // RAM SPI MOSI on IO0. IO1/2/3 are released by OE.
                core_data_out = {3'b111, ram_cmd_mosi};
            end

            C_RAM_ADDR: begin
                core_data_out = {3'b111, ram_byte_addr[core_count]};
            end

            C_RAM_DATA: begin
                if (core_is_writing)
                    core_data_out = {3'b111, core_write_word[core_count]};
                else
                    core_data_out = 4'b1111;
            end

            default: begin
                core_data_out = 4'b1111;
            end
        endcase
    end

endmodule


module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module Mux_2x1
(
    input [0:0] sel,
    input in_0,
    input in_1,
    output reg out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module singExtend (
  input [7:0] inst,
  output [15:0] \4S , // The four bits taken from Rs.
  output [15:0] \8SD , // The eight bits taken from Rs,Rd with sign extension.
  output [15:0] \4D  // The four bits taken from Rd.

);
  wire s0;
  assign \4D [3:0] = inst[7:4];
  assign \4D [15:4] = 12'b0;
  assign \4S [3:0] = inst[3:0];
  assign \4S [15:4] = 12'b0;
  assign s0 = inst[7];
  assign \8SD [6:0] = inst[6:0];
  assign \8SD [7] = s0;
  assign \8SD [8] = s0;
  assign \8SD [9] = s0;
  assign \8SD [10] = s0;
  assign \8SD [11] = s0;
  assign \8SD [12] = s0;
  assign \8SD [13] = s0;
  assign \8SD [14] = s0;
  assign \8SD [15] = s0;
endmodule

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule

// Oh boi
// Here is the decoder of the OPCODE to turn into microcode.
// I have an excel sheet to so you can "easily" see what each instruction changes.

module opcode_microcode_rom(
    input  [6:0] opcode,
    output muxb0,
    output muxb1,
    output muxb2,
    output aluop0,
    output aluop1,
    output aluop2,
    output aluop3,
    output aluop4,
    output WE,
    output sf,
    output iem0,
    output iem1,
    output br0,
    output br1,
    output br2,
    output muxA,
    output ld,
    output st,
    output abs,
    output ioW,
    output ioR,
    output stPC,
    output Reti,
    output flash_req,
    output BRK
);

reg [24:0] ctrl;

assign {
    muxb0,
    muxb1,
    muxb2,
    aluop0,
    aluop1,
    aluop2,
    aluop3,
    aluop4,
    WE,
    sf,
    iem0,
    iem1,
    br0,
    br1,
    br2,
    muxA,
    ld,
    st,
    abs,
    ioW,
    ioR,
    stPC,
    Reti,
    flash_req,
    BRK
} = ctrl;

always @(*) begin
    case (opcode)
        7'b0000000: ctrl = 25'b000_00000_000_0000_0000_00000_0;//8'hx00:
        7'b0000001: ctrl = 25'b000_00000_100_0000_1000_00000_0;//8'hx01:
        7'b0000010: ctrl = 25'b000_00001_110_0000_0000_00000_0;//8'hx02:
        7'b0000011: ctrl = 25'b000_10001_110_0000_0000_00000_0;//8'hx03:
        7'b0000100: ctrl = 25'b000_00010_110_0000_0000_00000_0;//8'hx04:
        7'b0000101: ctrl = 25'b000_10010_110_0000_0000_00000_0;//8'hx05:
        7'b0000110: ctrl = 25'b000_00011_110_0000_0000_00000_0;//8'hx06:
        7'b0000111: ctrl = 25'b000_00100_110_0000_0000_00000_0;//8'hx07:
        7'b0001000: ctrl = 25'b000_00101_110_0000_0000_00000_0;//8'hx08:
        7'b0001001: ctrl = 25'b010_00000_101_0000_0000_00000_0;//8'hx09:
        7'b0001010: ctrl = 25'b101_00000_100_0000_0000_00000_0;//8'hx0A:
        7'b0001011: ctrl = 25'b010_00001_111_0000_0000_00000_0;//8'hx0B:
        7'b0001100: ctrl = 25'b101_00001_110_0000_0000_00000_0;//8'hx0C:
        7'b0001101: ctrl = 25'b010_10001_111_0000_0000_00000_0;//8'hx0D:
        7'b0001110: ctrl = 25'b101_10001_110_0000_0000_00000_0;//8'hx0E:
        7'b0001111: ctrl = 25'b010_00010_111_0000_0000_00000_0;//8'hx0F:
        7'b0010000: ctrl = 25'b101_00010_110_0000_0000_00000_0;//8'hx10:
        7'b0010001: ctrl = 25'b010_10010_111_0000_0000_00000_0;//8'hx11:
        7'b0010010: ctrl = 25'b101_10010_110_0000_0000_00000_0;//8'hx12:
        7'b0010011: ctrl = 25'b000_00111_100_0000_0000_00000_0;//8'hx13:
        7'b0010100: ctrl = 25'b010_00011_111_0000_0000_00000_0;//8'hx14:
        7'b0010101: ctrl = 25'b101_00011_110_0000_0000_00000_0;//8'hx15:
        7'b0010110: ctrl = 25'b010_00100_111_0000_0000_00000_0;//8'hx16:
        7'b0010111: ctrl = 25'b101_00100_110_0000_0000_00000_0;//8'hx17:
        7'b0011000: ctrl = 25'b010_00101_111_0000_0000_00000_0;//8'hx18:
        7'b0011001: ctrl = 25'b101_00101_110_0000_0000_00000_0;//8'hx19:
        7'b0011010: ctrl = 25'b000_00110_100_0000_0000_00000_0;//8'hx1A:
        //17'b0011011:ctrl =58'b00_0011__1110_0000_0000_000000//8'hx1B:
        //17'b0011100:ctrl =58'b01_0011__1111_0000_0000_000000//8'hx1C:
        //17'b0011101:ctrl =58'b10_1011__1110_0000_0000_000000//8'hx1D:
        7'b0011110: ctrl = 25'b000_00010_010_0000_0000_00000_0;//8'hx1E:
        7'b0011111: ctrl = 25'b000_10010_010_0000_0000_00000_0;//8'hx1F:
        7'b0100000: ctrl = 25'b010_00010_011_0000_0000_00000_0;//8'hx20:
        7'b0100001: ctrl = 25'b101_00010_010_0000_0000_00000_0;//8'hx21:
        7'b0100010: ctrl = 25'b010_10010_011_0000_0000_00000_0;//8'hx22:
        7'b0100011: ctrl = 25'b101_10010_010_0000_0000_00000_0;//8'hx23:
        7'b0100100: ctrl = 25'b000_01000_110_0000_0000_00000_0;//8'hx24:
        7'b0100101: ctrl = 25'b000_01001_110_0000_0000_00000_0;//8'hx25:
        7'b0100110: ctrl = 25'b000_11000_110_0000_0000_00000_0;//8'hx26:
        7'b0100111: ctrl = 25'b000_11001_110_0000_0000_00000_0;//8'hx27:
        7'b0101000: ctrl = 25'b000_01010_110_0000_0000_00000_0;//8'hx28:
        7'b0101001: ctrl = 25'b000_01011_100_0000_0000_00000_0;//8'hx29:
        7'b0101010: ctrl = 25'b000_01100_100_0000_0000_00000_0;//8'hx2A:
        7'b0101011: ctrl = 25'b011_00001_000_0000_0010_00000_0;//8'hx2B:
        7'b0101100: ctrl = 25'b011_00001_100_0000_1100_00000_0;//8'hx2C:
        7'b0101101: ctrl = 25'b010_00000_001_1000_0010_00000_0;//8'hx2D:
        7'b0101110: ctrl = 25'b111_00000_000_0000_0010_00000_0;//8'hx2E:
        7'b0101111: ctrl = 25'b010_00000_101_0000_0100_00000_0;//8'hx2F:
        7'b0110000: ctrl = 25'b101_00000_100_0000_0100_00000_0;//8'hx30:
        7'b0110001: ctrl = 25'b010_00001_000_0000_0010_00000_0;//8'hx31:
        7'b0110010: ctrl = 25'b010_00001_100_0000_1100_00000_0;//8'hx32:
        7'b0110011: ctrl = 25'b001_00000_100_0000_0000_00000_0;//8'hx33:
        7'b0110100: ctrl = 25'b010_00000_001_0001_0000_00000_0;//8'hx34:
        7'b0110101: ctrl = 25'b010_00000_001_0010_0000_00000_0;//8'hx35:
        7'b0110110: ctrl = 25'b010_00000_001_0011_0000_00000_0;//8'hx36:
        7'b0110111: ctrl = 25'b010_00000_001_0101_0000_00000_0;//8'hx37:
        7'b0111000: ctrl = 25'b010_00000_001_0110_0000_00000_0;//8'hx38:
        7'b0111001: ctrl = 25'b010_00000_001_0111_0000_00000_0;//8'hx39:
        7'b0111010: ctrl = 25'b010_00000_101_0000_0001_00100_0;//8'hx3A:
        7'b0111011: ctrl = 25'b000_00000_000_0000_0001_00000_0;//8'hx3B:
        7'b0111100: ctrl = 25'b010_00000_001_0000_0001_00000_0;//8'hx3C:
        7'b0111101: ctrl = 25'b110_00000_000_0100_0000_00000_0;//8'hx3D:
        7'b0111110: ctrl = 25'b010_00000_001_1000_0000_10000_0;//8'hx3E:
        7'b0111111: ctrl = 25'b111_00000_000_0000_0000_10000_0;//8'hx3F:
        7'b1000000: ctrl = 25'b011_00001_000_0000_0000_10000_0;//8'hx40:
        7'b1000001: ctrl = 25'b010_00000_101_0000_1000_01000_0;//8'hx41:
        7'b1000010: ctrl = 25'b101_00000_100_0000_1000_01000_0;//8'hx42:
        7'b1000011: ctrl = 25'b011_00001_100_0000_1000_01000_0;//8'hx43:
        7'b1000100: ctrl = 25'b000_00000_000_0000_0001_00010_0;//8'hx44:
        7'b1000101: ctrl = 25'b011_00001_100_0000_1000_00001_0;//8'hx45:
        7'b1000110: ctrl = 25'b010_00000_101_0000_0000_00001_0;//8'hx46:
        7'b1000111: ctrl = 25'b101_00000_100_0000_0000_00001_0;//8'hx47:
        7'b1001000: ctrl = 25'b010_00001_100_0000_1000_00001_0;//8'hx48:
        7'b1001001: ctrl = 25'b000_00000_000_0000_1000_00000_1;//8'hx49:
        default:    ctrl = 25'b000_00000_000_0000_0000_00000_0;
    endcase
end

endmodule


module Mux_4x1
(
    input [1:0] sel,
    input in_0,
    input in_1,
    input in_2,
    input in_3,
    output reg out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule


// Register for storing large constants.
// There is a 1-bit command describing this register. 
// In this way, 15 bits can be stored (the 16th bit 
// activates the writing of this register and therefore 
// is always one). The 16th bit will be set according 
// to the 'immediate extend mode' (iem).
module ImReg (
  input en, // enables storage
  input [1:0] iem, // immediate extend mode (0: sign extend; 1: extend with 0, 2:extend with S0, 3:extend with D0)
  input C,
  input [15:0] inst, // the current instruction
  output [15:0] imm // The constant of register contents and bit 8.

);
  wire [14:0] s0;
  wire [14:0] s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  assign s2 = inst[0];
  assign s3 = inst[4];
  assign s0 = inst[14:0];
  // imm
  DIG_Register_BUS #(
    .Bits(15)
  )
  DIG_Register_BUS_i0 (
    .D( s0 ),
    .C( C ),
    .en( en ),
    .Q( s1 )
  );
  assign s5 = s1[14];
  Mux_4x1 Mux_4x1_i1 (
    .sel( iem ),
    .in_0( s5 ),
    .in_1( 1'b0 ),
    .in_2( s2 ),
    .in_3( s3 ),
    .out( s4 )
  );
  assign imm[14:0] = s1;
  assign imm[15] = s4;
endmodule
module muxEncoder
  (
    input a,
    input b,
    input c,
    input d,
    output reg [1:0]Q
  );

  always @ (a,b,c,d)
  begin

    Q[0] = | d | b ;
    Q[1] = | d | c ;

  end
endmodule


module Mux_4x1_NBits #(
    parameter Bits = 2
)
(
    input [1:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule

module lfsr_RandomNumberGen (
    input  [4:0] adrrIn,
    input  [7:0] dataIn,
    input         ioW,
    input         clk,
    input  [4:0] SeedAdr,
    input  [4:0] RngAdr,
    output [15:0] Out
);

    reg [7:0] seed_reg;
    reg [7:0] lfsr    ;

    wire seed_wr  = ioW && (adrrIn == SeedAdr);
    wire seed_rd  =  (adrrIn == SeedAdr);
    wire rng_rd   =  (adrrIn == RngAdr);

    // 8-bit maximal-length taps
    // polynomial: x^8 + x^6 + x^5 + x^4 + 1
    wire feedback = lfsr[7] ^ lfsr[5] ^ lfsr[4] ^ lfsr[3];

    always @(posedge clk) begin
        if (seed_wr) begin
            seed_reg <= dataIn[7:0];
            lfsr <= (dataIn[7:0] == 8'h00) ? 8'h01 : dataIn[7:0];
        end else begin
            lfsr <= {lfsr[6:0], feedback};
        end
    end

    assign Out = seed_rd ? {8'h00, seed_reg} :
                 rng_rd  ? {8'h00, lfsr}     :
                           16'h0000;

endmodule
module RegisterBlock (
    input  [15:0] DataIn,
    input         WE,
    input         clk,
    input  [3:0]  src,
    input  [3:0]  Dest,
    output [15:0] RDest,
    output [15:0] Rsrc
  );

  reg [15:0] regs [0:15];

  always @(negedge clk )
  begin

    if (WE)
    begin
      regs[Dest] <= DataIn;
    end
  end

  // read ports
  assign Rsrc  = regs[src];
  assign RDest = regs[Dest];

endmodule

module Alu (
    input [15:0] A,
    input [15:0] B,
    input carryIn,
    input [4:0] AluOp,
    output [15:0] Out,
    output Neg,
    output Zero,
    output CarryOut
  );
  wire use_carry;
  wire [3:0] sel;
  reg  [15:0] out_r;
  reg         carry_r;
  reg  [16:0] math_ext;

  assign use_carry = AluOp[4] & carryIn;
  assign sel = AluOp[3:0];

  always @(*)
  begin
    out_r   = 16'h0000;
    carry_r = 1'b0;
    math_ext = 17'h00000;

    case (sel)
      4'h0:
      begin // pass B through
        out_r = B;
      end

      4'h1:
      begin // add with optional carry
        math_ext = {1'b0, A} + {1'b0, B} + {{16{1'b0}}, use_carry};
        out_r    = math_ext[15:0];
        carry_r  = math_ext[16];
      end

      4'h2:
      begin // subtract with optional carry
        math_ext = {1'b0, A} - {1'b0, B} - {{16{1'b0}}, use_carry};
        out_r    = math_ext[15:0];
        carry_r  = math_ext[16];
      end

      4'h3:
      begin // bitwise AND
        out_r = A & B;
      end

      4'h4:
      begin // bitwise OR
        out_r = A | B;
      end

      4'h5:
      begin // bitwise XOR
        out_r = A ^ B;
      end

      4'h6:
      begin // bitwise NOT
        out_r = ~A;
      end

      4'h7:
      begin // negate (two's complement)
        math_ext = {1'b0, 16'h0000} - {1'b0, A};
        out_r    = math_ext[15:0];
      end

      4'h8:
      begin // shift left with optional carry
        out_r   = {A[14:0], use_carry};
        carry_r = A[15];
      end

      4'h9:
      begin // shift right with optional carry
        out_r   = {use_carry, A[15:1]};
        carry_r = A[0];
      end

      4'hA:
      begin // arithmetic shift right with optional carry
        out_r   = {A[15], A[15], A[14:1]};
        carry_r = A[0];
      end

      4'hB:
      begin // swap bytes
        out_r = {A[7:0], A[15:8]};
      end

      4'hC:
      begin // swap nibbles
        out_r = {A[11:8], A[15:12], A[3:0], A[7:4]};
      end

      default:
      begin // default to zero output
        out_r   = 16'h0000;
        carry_r = 1'b0;
      end
    endcase
  end

  assign Out      = out_r;
  assign CarryOut = carry_r;
  assign Neg      = out_r[15];
  assign Zero     = ~|out_r;
endmodule


module CompUnsigned #(
    parameter Bits = 1
)
(
    input [(Bits -1):0] a,
    input [(Bits -1):0] b,
    output \> ,
    output \= ,
    output \<
);
    assign \> = a > b;
    assign \= = a == b;
    assign \< = a < b;
endmodule


module tt_um_remedy_cpu (
  input [7:0] ui_in,
  input clk,
  input ena,
  input rst_n,
  input [7:0] uio_in,
  output [7:0] uo_out,
  output [7:0] uio_out,
  output [7:0] uio_oe
);
  wire muxA;
  wire [15:0] s0;
  wire [15:0] DataOut;
  wire [15:0] s1;
  wire [2:0] muxB;
  wire [15:0] ImmReg;
  wire [15:0] s2;
  wire [15:0] s3;
  wire [15:0] s4;
  wire [15:0] s5;
  wire [15:0] inst_reg;
  wire [3:0] s6;
  wire [3:0] s7;
  wire [7:0] OPcode;
  wire [1:0] s8;
  wire [15:0] AddrOut;
  wire [15:0] mem_out;
  wire [15:0] iow_Din;
  wire [15:0] s9;
  wire [15:0] s10;
  wire [1:0] s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire [2:0] br;
  wire [7:0] s16;
  wire imm;
  wire [1:0] iem;
  wire [15:0] inputReg;
  wire [7:0] inputFromOutside;
  wire [6:0] s17;
  wire [6:0] s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire [4:0] aluOp;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  wire s31;
  wire intr;
  wire \execute-pulse ;
  wire s32;
  wire Reti;
  wire s33;
  wire [4:0] s34;
  wire s35;
  wire ioW;
  wire s36;
  wire [7:0] s37;
  wire s38;
  wire sf;
  wire s39;
  wire s40;
  wire [7:0] outputToOutside;
  wire pc_en;
  wire s41;
  wire [15:0] deb_jump_addr;
  wire deb_jump_req;
  wire s42;
  wire jump_ack;
  wire [15:0] programAddr;
  wire s43;
  wire ioR;
  wire stPC;
  wire [15:0] outR;
  wire s44;
  wire WE;
  wire ld;
  wire data_done;
  wire s45;
  wire s46;
  wire Fetch_done;
  wire abs;
  wire [3:0] s47;
  wire [2:0] s48;
  wire [15:0] intr_reg;
  wire InterLock;
  wire s49;
  wire s50;
  wire i2c_inter;
  wire [7:0] s51;
  wire [15:0] rngdat0;
  wire [15:0] timerdat1;
  wire [8:0] s52;
  wire spi_busy_ram;
  wire [15:0] timerdat2;
  wire [2:0] s53;
  wire [15:0] i2cDat;
  wire [4:0] s54;
  wire s55;
  wire [3:0] s56;
  wire \sda-in ;
  wire sda_o;
  wire scl_o;
  wire scl_oe;
  wire sda_oe;
  wire st;
  wire flash_req;
  wire Break;
  wire s57;
  wire s58;
  wire s59;
  wire s60;
  wire s61;
  wire s62;
  wire s63;
  wire [2:0] flag_out;
  wire dbg_clk;
  wire dbg_data_in;
  wire [15:0] reg_rdata;
  wire dbg_data_out;
  wire dbg_data_oe;
  wire s64;
  wire [3:0] s65;
  wire [15:0] s66;
  wire s67;
  wire s68;
  wire s69;
  wire s70;
  wire dbg_en;
  wire halt_req;
  wire run_req;
  wire step_req;
  wire s71;
  wire s72;
  wire fetch_request_pulse;
  wire dbg_halted;
  wire [15:0] spi_data;
  wire spi_st;
  wire spi_ld;
  wire [15:0] spi_addr;
  wire [15:0] spi_data_out;
  wire spi_target;
  wire ststic_break_en;
  wire spics_flash;
  wire spi_clock;
  wire spics_ram;
  wire [3:0] qspi_data_in;
  wire [3:0] qspi_data_out;
  wire [3:0] qspi_data_oe;
  wire s73;
  wire s74;
  wire s75;
  wire s76;
  assign qspi_data_in[0] = uio_in[1];
  assign qspi_data_in[1] = uio_in[2];
  assign qspi_data_in[2] = uio_in[4];
  assign qspi_data_in[3] = uio_in[5];
  assign \sda-in  = uio_in[7];
  assign dbg_data_in = ui_in[6];
  assign dbg_clk = ui_in[7];
  assign inputFromOutside[5:0] = ui_in[5:0];
  assign inputFromOutside[6] = dbg_data_in;
  assign inputFromOutside[7] = dbg_clk;
  assign inputReg[0] = inputFromOutside[0];
  assign inputReg[1] = inputFromOutside[1];
  assign inputReg[2] = inputFromOutside[2];
  assign inputReg[3] = inputFromOutside[3];
  assign inputReg[4] = inputFromOutside[4];
  assign inputReg[5] = inputFromOutside[5];
  assign inputReg[6] = inputFromOutside[6];
  assign inputReg[7] = inputFromOutside[7];
  assign inputReg[15:8] = 8'b0;
  // NegR
  register_1bit register_1bit_i0 (
    .D( s38 ),
    .C( clk ),
    .en( sf ),
    .rst( rst_n ),
    .Q( s14 )
  );
  // ZeroR
  register_1bit register_1bit_i1 (
    .D( s39 ),
    .C( clk ),
    .en( sf ),
    .rst( rst_n ),
    .Q( s13 )
  );
  // CarryR
  register_1bit register_1bit_i2 (
    .D( s40 ),
    .C( clk ),
    .en( sf ),
    .rst( rst_n ),
    .Q( s12 )
  );
  // outputReg
  register_8bit register_8bit_i3 (
    .D( s37 ),
    .C( clk ),
    .en( s36 ),
    .rst( rst_n ),
    .Q( outputToOutside )
  );
  // programCounter
  programCounter programCounter_i4 (
    .AluIn( AddrOut ),
    .clk( clk ),
    .rst_n( rst_n ),
    .pc_en( pc_en ),
    .absJmp( s41 ),
    .intr( s32 ),
    .reti( s33 ),
    .deb_jump_addr( deb_jump_addr ),
    .deb_jump( deb_jump_req ),
    .relJmp( s42 ),
    .deb_jump_ack( jump_ack ),
    .PC( programAddr ),
    .PCNEXT( s9 )
  );
  // interrupt_controller_small
  interrupt_controller_small interrupt_controller_small_i5 (
    .dOut( s47 ),
    .Addr( s34 ),
    .ioW( ioW ),
    .C( clk ),
    .rst_n( rst_n ),
    .irq_in( s48 ),
    .imm( imm ),
    .reti( Reti ),
    .pc_en( pc_en ),
    .CPUInterruptEnableAddr( 5'b1101 ),
    .inputInterruptAddr( 5'b1110 ),
    .interruptRegAddr( 5'b1111 ),
    .InterruptOut( intr_reg ),
    .intr( intr ),
    .irq_lock( InterLock )
  );
  // timer
  timer timer_i6 (
    .dOut( DataOut ),
    .Addr( s34 ),
    .ioW( ioW ),
    .C( clk ),
    .InterLock( InterLock ),
    .timerConfigAddr( 5'b10 ),
    .timerTargetAddr( 5'b11 ),
    .timerResetAddr( 5'b100 ),
    .timerReadAddr( 5'b101 ),
    .timerSyncStartAddr( 5'b1010 ),
    .rst_n( rst_n ),
    .TimerOut( timerdat1 ),
    .timer_interrupt( s49 )
  );
  // timer_tiny
  timer_tiny timer_tiny_i7 (
    .dOut( s52 ),
    .Addr( s34 ),
    .ioW( ioW ),
    .C( spi_busy_ram ),
    .InterLock( InterLock ),
    .timerConfigAddr( 5'b110 ),
    .timerTargetAddr( 5'b111 ),
    .timerResetAddr( 5'b1000 ),
    .timerReadAddr( 5'b1001 ),
    .timerSyncStartAddr( 5'b1010 ),
    .rst_n( rst_n ),
    .TimerOut( timerdat2 ),
    .timer_interrupt( s50 )
  );
  Mux_8x1_NBits #(
    .Bits(16)
  )
  Mux_8x1_NBits_i8 (
    .sel( s53 ),
    .in_0( inputReg ),
    .in_1( outR ),
    .in_2( timerdat1 ),
    .in_3( timerdat2 ),
    .in_4( rngdat0 ),
    .in_5( intr_reg ),
    .in_6( i2cDat ),
    .in_7( i2cDat ),
    .out( iow_Din )
  );
  // i2c_master_ctrl
  i2c_master_ctrl i2c_master_ctrl_i9 (
    .clk( clk ),
    .rst_n( rst_n ),
    .wr_en( s55 ),
    .reg_addr( s56 ),
    .cpu_din( DataOut ),
    .sda_in( \sda-in  ),
    .cpu_dout( i2cDat ),
    .sda_out( sda_o ),
    .scl_out( scl_o ),
    .scl_oe( scl_oe ),
    .sda_oe( sda_oe ),
    .interrupt( i2c_inter )
  );
  // debug_serial_frontend
  debug_serial_frontend debug_serial_frontend_i10 (
    .cpu_clk( clk ),
    .rst_n( rst_n ),
    .dbg_clk( dbg_clk ),
    .dbg_data_in( dbg_data_in ),
    .reg_rdata( reg_rdata ),
    .dbg_data_out( dbg_data_out ),
    .dbg_data_oe( dbg_data_oe ),
    .reg_wr( s64 ),
    .reg_addr( s65 ),
    .reg_wdata( s66 )
  );
  // cpu_cycle_controller
  cpu_cycle_controller cpu_cycle_controller_i11 (
    .clk( clk ),
    .rst_n( rst_n ),
    .fetch_done( Fetch_done ),
    .data_done( data_done ),
    .ld( ld ),
    .st( st ),
    .flash_ld( flash_req ),
    .dbg_enable( dbg_en ),
    .dbg_halt_req( halt_req ),
    .dbg_run_req( run_req ),
    .dbg_step_req( step_req ),
    .dbg_break_hit( s71 ),
    .dbg_break_after_exec( s72 ),
    .fetch_req( fetch_request_pulse ),
    .execute_now_pulse( \execute-pulse  ),
    .dbg_halted( dbg_halted )
  );
  // memory_wait_controller
  memory_wait_controller memory_wait_controller_i12 (
    .clk( clk ),
    .rst_n( rst_n ),
    .fetch_req( fetch_request_pulse ),
    .ld_req( s67 ),
    .st_req( s68 ),
    .flash_req( s70 ),
    .fetch_addr( programAddr ),
    .data_addr( AddrOut ),
    .store_data( DataOut ),
    .spi_data_out( spi_data ),
    .spi_busy( spi_busy_ram ),
    .mem_rdata( mem_out ),
    .fetch_done( Fetch_done ),
    .data_done( data_done ),
    .mem_stall( s69 ),
    .spi_st( spi_st ),
    .spi_ld( spi_ld ),
    .spi_addr( spi_addr ),
    .spi_data_in( spi_data_out ),
    .spi_target( spi_target )
  );
  // debug_core
  debug_core debug_core_i13 (
    .clk( clk ),
    .rst_n( rst_n ),
    .reg_wr( s64 ),
    .reg_addr( s65 ),
    .reg_wdata( s66 ),
    .cpu_dbg_halted( dbg_halted ),
    .cpu_flags( flag_out ),
    .cpu_pc( programAddr ),
    .cpu_ir( inst_reg ),
    .instr_is_brk( Break ),
    .execute_now_pulse( \execute-pulse  ),
    .dbg_jump_ack( jump_ack ),
    .reg_rdata( reg_rdata ),
    .dbg_enable( dbg_en ),
    .dbg_halt_req( halt_req ),
    .dbg_run_req( run_req ),
    .dbg_step_req( step_req ),
    .static_break_enable( ststic_break_en ),
    .dbg_break_hit( s71 ),
    .dbg_break_after_exec( s72 ),
    .dbg_jump_req( deb_jump_req ),
    .dbg_jump_addr( deb_jump_addr )
  );
  // qspi_memory_interface
  qspi_memory_interface qspi_memory_interface_i14 (
    .clk( clk ),
    .spi_rst_n( rst_n ),
    .st( spi_st ),
    .ld( spi_ld ),
    .spi_target( spi_target ),
    .addr( spi_addr ),
    .data_in( spi_data_out ),
    .spi_data_in( qspi_data_in ),
    .data_out( spi_data ),
    .spi_clk( spi_clock ),
    .spi_flash_cs( spics_flash ),
    .spi_ram_cs( spics_ram ),
    .spi_data_out( qspi_data_out ),
    .spi_data_oe( qspi_data_oe ),
    .busy( spi_busy_ram )
  );
  assign s32 = (intr & \execute-pulse );
  assign outR[7:0] = outputToOutside;
  assign outR[15:8] = 8'b0;
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i15 (
    .D( mem_out ),
    .C( clk ),
    .en( Fetch_done ),
    .Q( inst_reg )
  );
  assign s48[0] = s49;
  assign s48[1] = s50;
  assign s48[2] = i2c_inter;
  assign flag_out[0] = s14;
  assign flag_out[1] = s13;
  assign flag_out[2] = s12;
  assign pc_en = (~ s69 & \execute-pulse );
  assign uio_out[0] = spics_flash;
  assign uio_out[1] = qspi_data_out[0];
  assign uio_out[2] = qspi_data_out[1];
  assign uio_out[3] = spi_clock;
  assign uio_out[4] = qspi_data_out[2];
  assign uio_out[5] = qspi_data_out[3];
  assign uio_out[6] = spics_ram;
  assign uio_out[7] = sda_o;
  assign uio_oe[0] = 1'b1;
  assign uio_oe[1] = qspi_data_oe[0];
  assign uio_oe[2] = qspi_data_oe[1];
  assign uio_oe[3] = 1'b1;
  assign uio_oe[4] = qspi_data_oe[2];
  assign uio_oe[5] = qspi_data_oe[3];
  assign uio_oe[6] = 1'b1;
  assign uio_oe[7] = sda_oe;
  assign s75 = outputToOutside[6];
  assign s76 = outputToOutside[7];
  Mux_2x1 Mux_2x1_i16 (
    .sel( dbg_data_oe ),
    .in_0( s76 ),
    .in_1( dbg_data_out ),
    .out( s74 )
  );
  Mux_2x1 Mux_2x1_i17 (
    .sel( scl_oe ),
    .in_0( s75 ),
    .in_1( scl_o ),
    .out( s73 )
  );
  assign s6 = inst_reg[3:0];
  assign s7 = inst_reg[7:4];
  assign OPcode = inst_reg[15:8];
  assign s16 = inst_reg[7:0];
  singExtend singExtend_i18 (
    .inst( s16 ),
    .\4S ( s2 ),
    .\8SD ( s3 ),
    .\4D ( s4 )
  );
  assign uo_out[5:0] = outputToOutside[5:0];
  assign uo_out[6] = s73;
  assign uo_out[7] = s74;
  assign s17 = OPcode[6:0];
  assign imm = OPcode[7];
  Mux_2x1_NBits #(
    .Bits(7)
  )
  Mux_2x1_NBits_i19 (
    .sel( imm ),
    .in_0( s17 ),
    .in_1( 7'b0 ),
    .out( s18 )
  );
  // opcode_microcode_rom
  opcode_microcode_rom opcode_microcode_rom_i20 (
    .opcode( s18 ),
    .muxb0( s21 ),
    .muxb1( s20 ),
    .muxb2( s19 ),
    .aluop0( s26 ),
    .aluop1( s25 ),
    .aluop2( s24 ),
    .aluop3( s23 ),
    .aluop4( s22 ),
    .WE( s44 ),
    .sf( s45 ),
    .iem0( s31 ),
    .iem1( s30 ),
    .br0( s29 ),
    .br1( s28 ),
    .br2( s27 ),
    .muxA( muxA ),
    .ld( ld ),
    .st( st ),
    .abs( abs ),
    .ioW( s46 ),
    .ioR( ioR ),
    .stPC( stPC ),
    .Reti( Reti ),
    .flash_req( flash_req ),
    .BRK( Break )
  );
  assign muxB[0] = s19;
  assign muxB[1] = s20;
  assign muxB[2] = s21;
  assign aluOp[0] = s22;
  assign aluOp[1] = s23;
  assign aluOp[2] = s24;
  assign aluOp[3] = s25;
  assign aluOp[4] = s26;
  assign br[0] = s27;
  assign br[1] = s28;
  assign br[2] = s29;
  assign iem[0] = s30;
  assign iem[1] = s31;
  assign s33 = (\execute-pulse  & Reti);
  assign WE = (((~ flash_req | ~ ld) & \execute-pulse  & s44) | (s44 & data_done & (flash_req | ld)));
  assign sf = (s45 & \execute-pulse );
  assign ioW = (s46 & \execute-pulse );
  assign s41 = (abs & \execute-pulse );
  assign s43 = (flash_req | ld);
  assign s67 = (ld & \execute-pulse );
  assign s68 = (\execute-pulse  & st);
  assign s70 = (\execute-pulse  & flash_req);
  ImReg ImReg_i21 (
    .en( imm ),
    .iem( iem ),
    .C( clk ),
    .inst( inst_reg ),
    .imm( ImmReg )
  );
  // muxEncoder
  muxEncoder muxEncoder_i22 (
    .a( 1'b0 ),
    .b( s43 ),
    .c( ioR ),
    .d( stPC ),
    .Q( s8 )
  );
  assign s11 = br[1:0];
  Mux_4x1 Mux_4x1_i23 (
    .sel( s11 ),
    .in_0( 1'b0 ),
    .in_1( s12 ),
    .in_2( s13 ),
    .in_3( s14 ),
    .out( s15 )
  );
  assign s42 = ((s15 ^ br[2]) & \execute-pulse );
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i24 (
    .sel( muxA ),
    .in_0( s0 ),
    .in_1( DataOut ),
    .out( s1 )
  );
  Mux_8x1_NBits #(
    .Bits(16)
  )
  Mux_8x1_NBits_i25 (
    .sel( muxB ),
    .in_0( DataOut ),
    .in_1( 16'b0 ),
    .in_2( ImmReg ),
    .in_3( 16'b0 ),
    .in_4( 16'b0 ),
    .in_5( s2 ),
    .in_6( s3 ),
    .in_7( s4 ),
    .out( s5 )
  );
  Mux_4x1_NBits #(
    .Bits(16)
  )
  Mux_4x1_NBits_i26 (
    .sel( s8 ),
    .in_0( AddrOut ),
    .in_1( mem_out ),
    .in_2( iow_Din ),
    .in_3( s9 ),
    .out( s10 )
  );
  assign s36 = (s35 & ioW);
  // lfsr_RandomNumberGen
  lfsr_RandomNumberGen lfsr_RandomNumberGen_i27 (
    .adrrIn( s34 ),
    .dataIn( s51 ),
    .ioW( ioW ),
    .clk( clk ),
    .SeedAdr( 5'b1011 ),
    .RngAdr( 5'b1100 ),
    .Out( rngdat0 )
  );
  // RegisterBlock
  RegisterBlock RegisterBlock_i28 (
    .DataIn( s10 ),
    .WE( WE ),
    .clk( clk ),
    .src( s6 ),
    .Dest( s7 ),
    .RDest( s0 ),
    .Rsrc( DataOut )
  );
  assign s55 = (s34[4] & ioW);
  // Alu
  Alu Alu_i29 (
    .A( s1 ),
    .B( s5 ),
    .carryIn( s12 ),
    .AluOp( aluOp ),
    .Out( AddrOut ),
    .Neg( s38 ),
    .Zero( s39 ),
    .CarryOut( s40 )
  );
  assign s37 = DataOut[7:0];
  assign s54 = AddrOut[4:0];
  assign s52 = DataOut[8:0];
  assign s51 = DataOut[7:0];
  assign s47 = DataOut[3:0];
  assign s34 = AddrOut[4:0];
  CompUnsigned #(
    .Bits(5)
  )
  CompUnsigned_i30 (
    .a( s34 ),
    .b( 5'b1 ),
    .\= ( s35 )
  );
  assign s56 = s34[3:0];
  assign s57 = s54[0];
  assign s58 = s54[1];
  assign s59 = s54[2];
  assign s60 = s54[3];
  assign s61 = s54[4];
  assign s62 = ~ s59;
  assign s63 = ~ s58;
  assign s53[0] = ((~ s61 & s62 & s63 & s57) | (s60 & s63 & s57) | (s60 & s62 & s63) | (s59 & s58));
  assign s53[1] = (s61 | (~ s60 & s58) | (~ s60 & s59) | (s60 & s62 & s63));
  assign s53[2] = (s61 | (s60 & s58 & s57) | (s60 & s59));
endmodule
